on:
    push:
      branches:
        - main
name: Alpha - Build & Deploy
env:
    GCP_PROJECT_NUMBER: 198262807868
    GCP_IDENTITY_POOL: prath-pool
    GCP_PROJECT_ID: earnest-triumph-390509
    GCP_SERVICE_ACCOUNT: github-oidc
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        
        steps:
        - uses: 'actions/checkout@v3'
    
        - id: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
            workload_identity_provider: 'projects/${{env.GCP_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/${{env.GCP_IDENTITY_POOL}}/providers/github'
            service_account: '${{env.GCP_SERVICE_ACCOUNT}}@${{env.GCP_PROJECT_ID}}.iam.gserviceaccount.com'

        # - id: 'deploy'
        #   uses: 'google-github-actions/deploy-cloud-functions@v1'
        #   with:
        #     name: 'email-processor'
        #     runtime: 'python311'
        #     memory_mb: '256'
        #     region: 'asia-south1'
        #     env_vars: 'WATCH_EMAIL=${{ secrets.WATCH_EMAIL }},WATCH_PASSWORD=${{ secrets.WATCH_PASSWORD }}'
        #     source_dir: './app'
        #     entry_point: 'handler'
        #     timeout: 300
        #     https_trigger_security_level: 'secure_always'
        #     min_instances: 0
        #     max_instances: 1

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'
          with:
            version: '>= 363.0.0'

        - id: 'deploy'
          run: > 
            gcloud functions deploy email-processor
            --region=asia-south1
            --source=./app
            --runtime=python311
            --entry-point=handler
            --memory=256
            --max-instances=1
            --set-env-vars=WATCH_EMAIL=${{ secrets.WATCH_EMAIL }},WATCH_PASSWORD=${{ secrets.WATCH_PASSWORD }}
            --timeout=300
            --allow-unauthenticated
            --trigger-http
            --gen2
    
        - id: 'test'
          run: 'curl "${{ steps.deploy.outputs.url }}"'